### PR TITLE
Standardize plugin behavior

### PR DESCRIPTION
**Pull request by neftaly**
This PR makes the webStorage plugin behave the same as the inMemory plugin on write. It also fixes an issue with the webStorage plugin, in that it ignores initial data.

### CODE REVIEW

**Comment by jameshopkins** [comment]
I absolutely agree with there being parity between the return value of the `write` methods for each plugin (that manages a synchronous transaction, at least), but I'm not sure which way to go :)

I'd like to understand what type of scenarios you envisage, where a consumer wouldn't immediately require a read operation *after* a synchronous transaction.

**Comment by neftaly** [comment]
I'll think of a proper answer tomorrow, but just want to note that this mirrors the current behavior of the localStorage API and other getter/setter libraries.

If it goes the other way, `this.read()` should be returned instead of rootState, as rootState is internal and not actually meant to be seen by the user. Or prehaps the atom itself (`this`) should be returned?

**Comment by neftaly** [comment]
```js
const inMemory = (data, transition) => {
  let rootState = data;
  const read = () => rootState;
  const write = (fn/*, ...context*/) => {
    const oldState = read();
    const newState = fn(oldState);
    transition(oldState, newState/*, ...context*/);
    rootState = newState;
    return read();
  };
  return { read, write };
};
```

**Comment by neftaly** [comment]
I've updated it so that values are returned on write

**Comment by jameshopkins** [comment]
> ...It also fixes an issue with the webStorage plugin, in that it ignores initial data.

Good spot :)

Can you write some suitable tests to cover both areas of functionality you've added in this PR? Once this is done, I'm happy to merge.

**Comment by neftaly** [comment]
The tests for f57cce3 and f4be150 will only check that data is being moved around, and not that it's actually the correct data, due to the nature of the localStorage stub. This is fixed in #3.

**Comment by jameshopkins** [comment]
OK, I'm happy to leave for now

**Comment by jameshopkins** [comment]
There's a failing test on this branch that needs fixing
```bash
1) Plugins Web reads:
     TypeError: store.setItem is not a function
```

**Comment by neftaly** [comment]
The tests should be good enough now (they are super imperative, instead of declarative, and check how stuff is being done, not what the actual result is).

**Comment by jameshopkins** [comment]
> they are really imperative, and check how stuff is being done, not what the actual result is

Yep they're admittedly not the best and can definitely be improved upon.

**Pull request merged**
